import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { ThemeProvider } from '@/contexts/theme-provider';
import AuthProvider from '@/contexts/auth-provider';
import GoogleOAuthProvider from '@/contexts/google-oauth-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AdFusion',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <GoogleOAuthProvider>
            <AuthProvider>{children}</AuthProvider>
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
